import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import ProviderComponent from "@/components/Provider";
import { Inter } from "next/font/google"


const inter = Inter({
  subsets:["latin"],
  display:"swap"
})
export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <ProviderComponent>
          <Header />
          {children}
        </ProviderComponent>
      </body>
    </html>
  );
}
